server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notifications
    username: postgres
    password: temojgark321
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

    mvc:
      view:
        prefix: /templates/
        suffix: .html
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace